### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [BharathVishal/App-Manager-for-Android#6]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Also, could you please attach signed release apk to your [releases](https://github.com/BharathVishal/App-Manager-Android/releases) so that people can easily download your app?

**Comment by BharathVishal** [comment]
Hi,
Thanks for your suggestion. I have added a signed apk to the latest release under the release folder. https://github.com/BharathVishal/App-Manager-Android/tree/master/Releases

**Comment by BharathVishal** [comment]
Hi,
Thanks for your suggestion. I have added a signed apk of the latest version that adds splash screen support and Jetpack Compose UI to the release folder. 
Here's the link: https://github.com/BharathVishal/App-Manager-Android/tree/master/Releases

**Comment by Poussinou** [comment]
Attaching the apk to the Release section is better, because people can update it more easily, via the Github notifications for example. Uploading binaries directly in the repo isn't something recommended.

So, is the F-Droid inclusion ok for you? :)
